inherit: 
    - models/tiny.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 51

training:
    task: relu_2nn_regression
    task_kwargs: {"hidden_layer_size": 10}
    data: gaussian
    batch_size: 64
    learning_rate: 0.00005
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 10001
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 21
            end: 51
            inc: 10
            interval: 2000

out_dir: ../models/relu_2nn_regression

wandb:
    name: "relu_2nn_regression_standard"
